### ISSUE TITLE
Currently unable to be installed via the AUR on artix linux

### ISSUE THREAD

**Issue by JulianWogersien** [SpyHoodle/PrideFetch#23]
Neither manual nor with yay works because it doesn't pass the validity check

**Comment by R0dn3yS** [comment]
Fixed the package, should pass the check now.

**Comment by JulianWogersien** [comment]
not 100% sure about artix, i am currently on my manjaro pc however here when yay attempts to update pridefetch it fails to validate the source files with sha512sums.

**Comment by JulianWogersien** [comment]
i was able to install it manually though so it might be an issue with yay

**Comment by R0dn3yS** [comment]
Forgot to increase the release version of the package, everything should be fine now.
