### ISSUE TITLE
Package count differs from `pfetch` and `neofetch` on RHEL 8

### ISSUE THREAD

**Issue by datho7561** [SpyHoodle/PrideFetch#24]
Just tried this out on RHEL 8.7 through `nix-shell -p pridefetch`

`neofetch` and `pfetch` both list the number of (`dnf`) packages as 2063, but `pridefetch` lists it as 2040.

**Comment by datho7561** [comment]
I see; `rpm -qa | wc -l` gives 2063, whereas `dnf list installed | wc -l` gives 2040. I'll investigate to see what the different packages are. Maybe they are something that dnf/yum uses internally like package group packages, in which case the 2040 would probably be better to report.

**Comment by datho7561** [comment]
None of the implementations are correct
- the rpm based method includes installed gpg keys as packages in the counted number
- the dnf method counts some output text as packages that shouldn't be. eg. on my computer the output starts with:
```
Not root, Subscription Management repositories not updated
Installed Packages
```
then the packages are listed. (Note that this output **isn't** completely silenced with the `-q` option)

**Comment by datho7561** [comment]
submitted to neofetch as well

**Comment by SpyHoodle** [comment]
Hi there, what would you recommend as the best command(s) for your system? If both neofetch and pridefetch are wrong, then we have nothing to go off of.

Thanks for submitting your issue, and I apologise for the delay.

**Comment by datho7561** [comment]
Thanks for the response, and no worries about the delay, I had to to a bit of digging to figure out what was happening and should have held off on submitting this until I understood the problem better.

The easiest way to get the number of packages is to run `dnf list installed -q | tail -n +2 | wc -l`. (skip the first line of output, since it's just a title that `dnf` prints out). This should give a 1 or 2 package difference from the current command.

The actual bug I ran into is against `neofetch`: sometimes it uses `rpm` instead of `dnf` when both are installed, even though `dnf` will give a more accurate number of packages.

**Comment by SpyHoodle** [comment]
@datho7561 I have created #25, it seems that `YUM` is also affected by this issue too, so I have fixed that as well.

**Comment by datho7561** [comment]
Thanks!

**Comment by datho7561** [comment]
Sorry, just tried it out, and it seems like the python library to run the command doesn't like the pipe in the command. I'll see if I can come up with something else.
