### ISSUE TITLE
MacOS support

### ISSUE THREAD

**Issue by megamichelle** [SpyHoodle/PrideFetch#28]
> ~/Downloads/pridefetch/src(master)$ python3 __main__.py 
> Traceback (most recent call last):
>   File "/Users/michelle/Downloads/pridefetch/src/__main__.py", line 17, in <module>
>     from time import clock_gettime, CLOCK_BOOTTIME
> ImportError: cannot import name 'CLOCK_BOOTTIME' from 'time' (unknown location)
> ~/Downloads/pridefetch/src(master)$ python3 --version
> Python 3.11.2

This is MacOS Ventura 13.4 on Apple Silicon, with python3 from Homebrew.

**Comment by SpyHoodle** [comment]
#27 has completed this.
