### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by Minion3665** [SpyHoodle/PrideFetch#3]
This project was originally created by @megabytesofrem; and there is no license. As we need to have a license I'm doing my best to contact megabytesofrem; I'll keep you posted in this issue

**Comment by Minion3665** [comment]
![2022-05-22 22:42:49+01:00](https://user-images.githubusercontent.com/34243578/169717316-a01271ae-9d02-4bfd-8407-5a752583aa16.png)
Based on permission from megabytesofrem (see attached screenshot) this project is now licensed under the MIT license

**Comment by megabytesofrem** [comment]
I'll give the project a star when I get back on my computer :)
