### ISSUE TITLE
Packaging status for Arch Linux

### ISSUE THREAD

**Issue by SpyHoodle** [SpyHoodle/PrideFetch#8]
So far, we're thinking of having a PKGBUILD, which zips the contents src directory into a file like `pridefetch.zip` then, adds a python shebang to the zip to make it an executable file.

The relevant code is here:
```bash
cd src
zip -r ../pridefetch.zip *
cd ..
echo '#!/usr/bin/env python' | cat - pridefetch.zip > pridefetch
rm pridefetch.zip
```

This is to better solve pull request #6, so that we can continue using multiple files during development, but the user gets one executable file installed nicely into their system. This system of zipping can also be applied for other distributions.

**Comment by R0dn3yS** [comment]
Yes this works, I'll make the new PKGBUILD and upload it to the AUR.
