### ISSUE TITLE
Packaging status for NixOS (flakes)

### ISSUE THREAD

**Issue by SpyHoodle** [SpyHoodle/PrideFetch#9]
This issue is for keeping track of packaging in NixOS. The nix flake will have to be adjusted to suit a new src directory style structure. As discussed in issue #8 we are taking a zipping approach for systems which would find it easier with one single executable file. Other than the directory restructure, this zipping should not affect the Nix flake, as it's likely going to be done by the install script for each distribution, as far as I'm aware.

**Comment by Minion3665** [comment]
Awesome! I'll fix this in https://github.com/SpyHoodle/pridefetch/tree/packaging; as that's where the restructure is being done

**Comment by Minion3665** [comment]
As of a0122e1beecf5479292f1102fb9eb530445fe446, the flake is now up-to-date with the new directory structure

**Comment by Minion3665** [comment]
When #10 is closed, it would be nice to make the flake a mirror of that (overridden to have a new src and a postBuild hook that cleans up (if the hook is needed; I'm not sure of the actual behavior of flakes when building and have just realized there is ~100% chance that this happens all in the nix-store))
